- Cartfile
- Cartfile.private
This pull request reflects the changes discussed in Carthage/Carthage#331 and Carthage/Carthage#332.
Fixes #31.
> Fix private dependencies.

- CHANGELOG.md
- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/OffsetMap.swift
- Source/SourceKittenFramework/Optional+SourceKitten.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
- Source/SourceKittenFramework/SwiftDocKey.swift
- Source/SourceKittenFramework/SyntaxToken.swift
- Source/SourceKittenFrameworkTests/Fixtures/Bicycle.json
- Source/SourceKittenFrameworkTests/Fixtures/Subscript.json
- Source/SourceKittenFrameworkTests/StringTests.swift
- sourcekitten.xcodeproj/project.pbxproj
Needed for https://github.com/realm/jazzy/issues/198. /cc @segiddins
> Added definition line ranges to declarations.

- README.md
Mostly copied from https://github.com/Carthage/Carthage#carthagekit, and in response to #73.
> [README] add SourceKittenFramework section

- .travis.yml
- CHANGELOG.md
- Source/SourceKittenFramework/SwiftDeclarationKind.swift
- Source/SourceKittenFramework/SyntaxKind.swift
- Source/SourceKittenFrameworkTests/Fixtures/Commandant.json
- Source/SourceKittenFrameworkTests/Fixtures/SimpleCodeCompletion.json
- Source/SourceKittenFrameworkTests/SourceKitTests.swift
Fixes #69. Will fail on CI because Travis doesn't have Xcode 7.1 Beta 2 images yet :disappointed:.
> Updated for Xcode 7.1 GM

- Cartfile
- Cartfile.private
- Cartfile.resolved
- Source/SourceKittenFrameworkTests/Fixtures/Commandant.json
> Update dependencies whose branches no longer exist

- CHANGELOG.md
- Source/SourceKittenFramework/Structure.swift
> Don't process SourceKit's response when building Structure

- Source/SourceKittenFramework/Clang+SourceKitten.swift
libClang considers enums declared like `typedef enum {} name;` rather than `NS_ENUM()`
to have a cursor spelling of "" (empty string). So we parse the USR to extract the actual name.
This fixes https://github.com/realm/jazzy/issues/342 /cc @jverkoey
> fix empty Objective-C enum names

- CHANGELOG.md
- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/Xcode.swift
- Source/sourcekitten/CompleteCommand.swift
- Source/sourcekitten/StructureCommand.swift
- Source/sourcekitten/SyntaxCommand.swift
Picked up from #44. Turns out I *do* like that approach :wink: /cc @neonichu
Snuck in a few small refactorings in this. Shhhhhh.
> increase robustness of file path handling

- .gitignore
- Makefile
- Releasing.md
should simplify the release process
> add 'archive' and 'release' actions to Makefile

- Source/SourceKittenFramework/String+SourceKitten.swift
Rename `ByteOffsetCache` to `CacheContainer`
Add `lineAndCharacterForCharacterOffset(_:)` to `CacheContainer`
Linting KeychainAccess by SwiftLint(3837c73), SourceKitten(668d974)
Before applying this commit:
```
$ time swiftlint
…
swiftlint  10.74s user 0.17s system 95% cpu 11.438 total
```
After this commit applied:
```
$ time swiftlint
…
swiftlint  7.89s user 0.17s system 95% cpu 8.453 total
```
> Optimize performance of `lineAndCharacterForCharacterOffset(_:)`

- Source/SourceKittenFramework/String+SourceKitten.swift
Add `NSString.CacheContainer.lineAndCharacterForByteOffset(_:)`
This commit reduces the duration of linting KeychainAccess by SwiftLint (8d529f1) from:
```
swiftlint lint  27.27s user 0.25s system 96% cpu 28.424 total
```
to:
```
swiftlint lint  3.76s user 0.10s system 89% cpu 4.291 total
```
This is that I mentioned in #127
> Optimize NSString.lineAndCharacterForByteOffset()

- Source/SourceKittenFramework/String+SourceKitten.swift
- Simplify `NSString.CacheContainer`  
Remove `byteOffsetIndexPairs`
- Add `NSString.CacheContainer.locationFromByteOffset(_:)`  
Rewrite `NSString. byteRangeToNSRange(_:)` to use that.
No performance gain by this PR because ` byteRangeToNSRange` is not heavily used yet.
But I think that will be heavily used for fixing such as https://github.com/realm/SwiftLint/issues/294.
> Optimize `NSString. byteRangeToNSRange(_:)`

- Source/SourceKittenFramework/String+SourceKitten.swift
just a few minor tweaks to #130.
> tweak changes from #130 a bit

- CHANGELOG.md
- Source/SourceKittenFramework/ObjCDeclarationKind.swift
Addresses realm/jazzy#452 /cc @rastersize
> Add support for parsing module imports in Objective-C

- Source/SourceKittenFramework/Dictionary+Merge.swift
- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/Module.swift
- Source/SourceKittenFramework/OffsetMap.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
- Source/SourceKittenFramework/Structure.swift
- Source/SourceKittenFramework/SwiftDocs.swift
- Source/SourceKittenFramework/Xcode.swift
like `var` in function parameters and ++
> avoid features deprecated in Swift 2.2

- Source/SourceKittenFramework/Request.swift
- Add `sourceKittenRawValueStringFrom(_:)` and comments for #148
- By applying this,The duration of linting Carthage 0.11 by SwiftLint(8af5c4e)
with SourceKitten(6025179) is reduced from:
```
swiftlint lint --config ~/.swiftlint-test.yml  18.34s user 1.14s system 83% cpu 23.271 total
```
to:
```
swiftlint lint --config ~/.swiftlint-test.yml  17.60s user 1.13s system 85% cpu 22.014 total
```
Adding enums mentioned in #148 will be separated PR.
> Use Swift's native `String` instead of `NSString` based `String`

- CHANGELOG.md
- Source/SourceKittenFramework/String+SourceKitten.swift
This allows more performance optimizations on SwiftLint.
> Change `Line` from tuple to struct with extra properties `range` and `byteRange`

- .travis.yml
- Makefile
- Package.swift
- Source/SourceKittenFrameworkTests/ClangTranslationUnitTests.swift
- Source/SourceKittenFrameworkTests/CodeCompletionTests.swift
- Source/SourceKittenFrameworkTests/FileTests.swift
- Source/SourceKittenFrameworkTests/ModuleTests.swift
- Source/SourceKittenFrameworkTests/OffsetMapTests.swift
- Source/SourceKittenFrameworkTests/SourceKitTests.swift
- Source/SourceKittenFrameworkTests/StringTests.swift
- Source/SourceKittenFrameworkTests/StructureTests.swift
- Source/SourceKittenFrameworkTests/SwiftDocsTests.swift
- Source/SourceKittenFrameworkTests/SyntaxTests.swift
- Source/SourceKittenFrameworkTests/main.swift
- sourcekitten.xcodeproj/project.pbxproj
> Run unit tests with SPM

- CHANGELOG.md
- Source/SourceKittenFramework/Request.swift
> Support string in other than NSUTF8StringEncoding returned from SourceKitService

- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/SyntaxMap.swift
- Tests/SourceKittenFramework/Fixtures/Commandant.json
Fixes https://github.com/jpsim/SourceKitten/pull/175#issuecomment-198107337
> skip annotation commands in commentRangeBeforeOffset

- Source/SourceKittenFramework/ClangTranslationUnit.swift
- Tests/SourceKittenFramework/ClangTranslationUnitTests.swift
- Tests/SourceKittenFramework/CodeCompletionTests.swift
- Tests/SourceKittenFramework/ModuleTests.swift
- Tests/SourceKittenFramework/SwiftDocsTests.swift
to simplify code and easily allow updating fixtures
> refactor how JSON comparisons work

- CHANGELOG.md
- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
- Tests/SourceKittenFramework/Fixtures/Commandant.json
- sourcekitten.xcodeproj/xcshareddata/xcschemes/sourcekitten.xcscheme
> fix bug where parsed declaration would include body

- LICENSE
The README.md states that the source is MIT licensed but there is no LICENSE in the repo.
> Add MIT LICENSE to root of repo.

- Cartfile
- Cartfile.private
- Cartfile.resolved
- Source/SourceKittenFramework/File.swift
This should be required for Swift 2.3 support on SwiftLint (related to https://github.com/realm/SwiftLint/issues/815).
> Stable Swift 2.3 support

- .travis.yml
- Dangerfile
This PR should fail, as you'll need to set up the access token as with Jazzy. 👍
> Adds a Dangerfile to SourceKitten

- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
This may have some performance implications. @norio-nomura what do you think? I pulled this out of #223.
> Refactor a few things in String+SourceKitten

- CHANGELOG.md
- Makefile
- Source/SourceKittenFramework/Info.plist
- Source/sourcekitten/Info.plist
- Source/sourcekitten/VersionCommand.swift
To fix build error on https://github.com/Homebrew/homebrew-core/pull/5094
> Fix Homebrew bottling error

- Source/SourceKittenFramework/CodeCompletionItem.swift
- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/Language.swift
- Source/SourceKittenFramework/ObjCDeclarationKind.swift
- Source/SourceKittenFramework/OffsetMap.swift
- Source/SourceKittenFramework/Request.swift
- Source/SourceKittenFramework/SourceDeclaration.swift
- Source/SourceKittenFramework/SourceLocation.swift
- Source/SourceKittenFramework/StatementKind.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
- Source/SourceKittenFramework/SwiftDeclarationKind.swift
- Source/SourceKittenFramework/SwiftDocKey.swift
- Source/SourceKittenFramework/SyntaxKind.swift
- Source/SourceKittenFramework/SyntaxMap.swift
- Source/SourceKittenFramework/Xcode.swift
> Add `@available` to swift 3 api guidelines changes

- Source/SourceKittenFramework/File.swift
This fixes #280.
Another compiler crashing issue still remains on Xcode 8.1 GM seed.
> Add workaround of #280

- CHANGELOG.md
- Source/SourceKittenFramework/Request.swift
- Tests/LinuxMain.swift
- Tests/SourceKittenFrameworkTests/DocInfoTests.swift
- Tests/SourceKittenFrameworkTests/Fixtures/DocInfo.json
- Tests/SourceKittenFrameworkTests/Fixtures/DocInfo.swift
- Tests/SourceKittenFrameworkTests/Fixtures/ModuleInfo.json
- sourcekitten.xcodeproj/project.pbxproj
This change adds Request support for two of the SourceKit docinfo variants.
> Adds support for docinfo requests.

- Source/SourceKittenFramework/Request.swift
- Tests/LinuxMain.swift
- Tests/SourceKittenFrameworkTests/DocInfoTests.swift
and minor formatting fixes. Follow up to #279.
> Run DocInfoTests on Linux

- CHANGELOG.md
- Source/SourceKittenFramework/SourceDeclaration.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
- Tests/SourceKittenFrameworkTests/Fixtures/Musician.h
- Tests/SourceKittenFrameworkTests/Fixtures/Musician.json
> Supprt Objective-C class properties

- Source/SourceKittenFramework/Module.swift
- Tests/LinuxMain.swift
- Tests/SourceKittenFrameworkTests/Fixtures/CommandantSPM.json
- Tests/SourceKittenFrameworkTests/ModuleTests.swift
YamlSwift takes over a minute to parse `debug.yaml` on Linux! As soon as I figure out how to profile Swift on Linux for performance, I'll look into this more.
> Add unit test for SPM docs

- .travis.yml
the sneakpeek one will go away soon
> use xcode8.1 image on Travis

- Cartfile.resolved
- SourceKitten.podspec
- sourcekitten.xcodeproj/project.pbxproj
Waiting for behrang/YamlSwift#45 and drmohundro/SWXMLHash#106 to be merged and released.
> Allow use in app extensions

- .travis.yml
- sourcekitten.xcodeproj/project.pbxproj
to fix compilation with Xcode 8.2. A different take on #316 which attempted to do the same thing.
> update SWIFT_VERSION in Xcode project to '3.0'

- Makefile
- Releasing.md
- Source/sourcekitten/VersionCommand.swift
- SourceKitten.podspec
I did the same thing to SwiftLint two weeks ago: realm/SwiftLint#937
> Automate actions around versions

- CONTRIBUTING.md
- Fixed spelling mistake on line 10.
- Added ` around CHANGELOG.md.
- Added a link to CocoaPods' change log.
> Minor grammar and consistency improvements

- Source/SourceKittenFramework/Request.swift
The UID cache was added over 2 years ago in fe2cca6 and its impact was never revisited until now.
Prompted by @krzysztofzablocki, I measured the impact of a few common operations with and without the cache and determined that it should be removed, since it hurts more than it helps.
Especially after the lock was added in #327. Even before the lock, the gains were minimal.
SourceKitten unit tests
* with cache: 44.7s
* without cache: 45.8s
Vapor 1.3.8 with `doc --spm-module Vapor`
* with cache: 24.75s
* without cache: 21.52s
SwiftLint linting the Swift stdlib
* with cache: 43.7s
* without cache: 25.2s
> remove UID map and lock

- Cartfile.resolved
- Package.swift
- Source/SourceKittenFramework/library_wrapper.swift
This depends on https://github.com/drmohundro/SWXMLHash/pull/120 and will wait merging that.
Tests are still failing on Xcode 8.3, but this PR won't fix them.
> Support building on Xcode8.3

- jazzy.sh
the module name was incorrectly set to 'SourceKitten' when it should've been 'SourceKittenFramework'.
> fix jazzy.sh and set version when running

- Source/SourceKittenFramework/ClangTranslationUnit.swift
- Source/SourceKittenFramework/JSONOutput.swift
[SE-0110](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md)
> [SE-0110] Distinguish between single-tuple and multiple-argument function types

- sourcekitten.xcodeproj/project.pbxproj
Fixes:
```
Source/sourcekitten/VersionCommand.swift:18:15: error: use of unresolved identifier 'Version'
print(Version.current.value)
^~~~~~~
```
> Add `Version.swift` to `project.pbxproj`

- Source/SourceKittenFramework/SourceDeclaration.swift
> Improve accessorUSR(getter:) build time

- README.md
- Source/sourcekitten/main.swift
So many awesome projects have been built on top of this, it's worth calling out, and it might help folks who want to build things themselves get inspired and see real-world sample code using SourceKitten.
> Add "Projects Built With SourceKitten" section to README

- .circleci/config.yml
Trying to resolve #450 by using [Caching Dependencies](https://circleci.com/docs/2.0/caching/).
> Cache `~/.cocoapods` on CircleCI

- README.md
https://github.com/yonaskolb/Beak
> Add Beak to SourceKitten projects

- CHANGELOG.md
- Cartfile.private
- Cartfile.resolved
- Makefile
- Package.swift
- Tests/SourceKittenFrameworkTests/Fixtures/Commandant@swift-3.2.json
> Update Commandant to 0.13.0

- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/OffsetMap.swift
- Source/SourceKittenFramework/Request.swift
- Source/SourceKittenFramework/SwiftDocKey.swift
> [SwiftDocKey] Change `getSubstructure` return type to `[[String: SourceKitRepresentable]]?`

- CHANGELOG.md
- Source/sourcekitten/ModuleInfoCommand.swift
- Source/sourcekitten/main.swift
- sourcekitten.xcodeproj/project.pbxproj
Exposes the `moduleInfo` request via the frontend.
> Adds a module_info command to SourceKitten frontend.

- CHANGELOG.md
- Source/SourceKittenFramework/library_wrapper.swift
Lightly tested on recent Ubuntu release.
> Fix a problem locating the source kit shared library on linux.

- README.md
I added Weaver, which is another cool project with code generation features built with SourceKitten. 
Weaver is a declarative, easy-to-use and safe Dependency Injection framework for Swift.
- Declarative because it allows to declare dependencies via annotations directly in the Swift code.
- Easy-to-use because it generates the necessary boilerplate code to inject dependencies into Swift types.
- Safe because it validates the dependency graph at compile time and outputs a nice XCode error when something's wrong.
You can check it out on GitHub: https://github.com/scribd/Weaver
I also wrote this article explaining why I developed it: https://medium.com/scribd-data-science-engineering/weaver-a-painless-dependency-injection-framework-for-swift-7c4afad5ef6a
> Added Weaver to the list of projects with SourceKitten

- CHANGELOG.md
- Source/SourceKittenFramework/Request.swift
https://bugs.swift.org/browse/SR-7954
This is separated from https://github.com/jpsim/SourceKitten/pull/527.
> Apply workaround for #529

- README.md
I added FactoryProvider, which is another cool project with code generation features built with SourceKitten.
FactoryProvider is Generate boilerplate of factory Swift framework.
You can check it out on GitHub: https://github.com/Nonchalant/FactoryProvider
> Added FactoryProvider to the list of projects with SourceKitten

- .circleci/config.yml
- .swiftlint.yml
- Source/SourceKittenFramework/JSONOutput.swift
- Source/SourceKittenFramework/Request.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
and use glob syntax for excluded files.
> Enable more SwiftLint rules

- Source/SourceKittenFramework/Request.swift
- Tests/SourceKittenFrameworkTests/Fixtures/BicycleSyntax.json
- Tests/SourceKittenFrameworkTests/SourceKitTests.swift
For getting a JSON-serialized representation of a file's [SwiftSyntax](https://github.com/apple/swift-syntax) tree.
> Add Request.syntaxTree

- Package.resolved
- Package.swift
This is an upstream requirement for https://github.com/uber/needle/issues/283
> Update SWXMLHash to 4.9.0 to support Xcode 10.2

- Package.swift
Resolves https://github.com/jpsim/SourceKitten/issues/590
> Pin Commandant to 0.16.x

- CHANGELOG.md
- Source/SourceKittenFramework/CursorInfo+Parsing.swift
- Tests/LinuxMain.swift
- Tests/SourceKittenFrameworkTests/CursorInfoParsingTests.swift
- sourcekitten.xcodeproj/project.pbxproj
From https://github.com/realm/SwiftLint/pull/2818
@jpsim Is this what you had in mind? or something else?
> Move CursorInfo referenced USR code from swiftlint

- CHANGELOG.md
- Source/SourceKittenFramework/Clang+SourceKitten.swift
- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/Line.swift
- Source/SourceKittenFramework/SourceDeclaration.swift
- Source/SourceKittenFramework/String+SourceKitten.swift
- Source/SourceKittenFramework/StringView+SourceKitten.swift
- Source/SourceKittenFramework/StringView.swift
- Source/SourceKittenFramework/SwiftDocs.swift
- Tests/SourceKittenFrameworkTests/OffsetMapTests.swift
- Tests/SourceKittenFrameworkTests/StringTests.swift
- sourcekitten.xcodeproj/project.pbxproj
- Removing cache from NSstring
- The cache was replaced by StringView property
> Use StringView instead of excessive caching in NSString

- Source/SourceKittenFramework/ByteCount.swift
- Source/SourceKittenFramework/ByteRange.swift
- Tests/LinuxMain.swift
- Tests/SourceKittenFrameworkTests/ByteRangeTests.swift
- sourcekitten.xcodeproj/project.pbxproj
Added function and opened some methods, potentially required when using SourceKiten.
> Update Framework API visibility

- Cartfile
- Cartfile.resolved
Looks like this was missed in #649.
> Update Yams version in Cartfile

- azure-pipelines.yml
Azure Pipelines removed support for that recently.
> Remove Xcode 11 CI job

- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
This will automatically publish releases to bazel-central-registry
> Add `.bcr` configuration files

- .github/workflows/swiftlint.yml
- Source/SourceKittenFramework/File.swift
- Source/SourceKittenFramework/StatementKind.swift
These are new in 0.52.2.
Also update CI to run SwiftLint 0.52.2
> Address new SwiftLint violations

- CHANGELOG.md
- Makefile
Fixes https://github.com/jpsim/SourceKitten/issues/793
> Stop building with `-static-stdlib`
