README.md
Just ran into this small issue: downloaded the master branch as zip file. Didn't see that this project depends on git submodules, so installation failed.
We could also mention that ZIP download + using carthage to install dependencies works as well, but I think that would be overkill.
=> Mention that git clone should be used for installation

CHANGELOG.md, Source/SourceKittenFramework/ClangTranslationUnit.swift, Source/SourceKittenFramework/Language.swift, Source/SourceKittenFramework/Module.swift
Until we find a way to index an Xcode project programmatically, or to avoid relying on sending `cursor.info` requests to get docs, we'll have to default to actually building the scheme being documented.
I also updated the xcodebuild argument filtering based on trial and error, comparing the arguments from `xcodebuild` to what Xcode sends to SourceKit.
=> don't automatically pass in `-dry-run` when running xcodebuild

.travis.yml, README.md
This reverts commit 425c950350c9086b0527129e64ae9b0cbe0e6d74.
=> Revert "[Travis] remove .travis.yml until it supports Xcode 6.3.1"

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/String+SourceKitten.swift
This adds a lines accessory to File. This can be useful if you want to iterate over all lines in the file multiple times.
This will be super useful in [SwiftLint](https://github.com/realm/SwiftLint) where the same file is being used over and over and the contents of that file are broken into these lines many times. If this PR looks good I'll submit one to SwiftLint with the necessary changes.
The one downside to this is the file needs to be a `var` since this property is lazy. I think that is preferred over setting the lines for every file since they won't always be used.
=> Add File lines convenience method

CHANGELOG.md, Source/SourceKittenFramework/File.swift
This is a follow up to https://github.com/jpsim/SourceKitten/pull/60
In that PR I said:
> The one downside to this is the file needs to be a `var` since this property is lazy. I think that is preferred over setting the lines for every file since they won't always be used.
I began to implement this in SwiftLint and the changes were pretty severe. Having to make everything a `var` for this, especially with the recent comment region addition, became very ugly very fast.
Again this has the downside that if this property is unused, this is wasted. In the case of SwiftLint this probably won't ever be the case, but in other applications I'm sure it could be.
I wasn't sure where this change would fit into the changelog so I didn't add anything yet, let me know what makes sense and I'll add it. …
=> Make File lines a immutable property

Source/sourcekitten/CompleteCommand.swift
conditions that return .failure enum will be only when it fails to read the file.
=> fix '--file' option

CHANGELOG.md, README.md, Source/sourcekitten/CompleteCommand.swift
To use the iOS SDK is "complete" command, `-target` option must also be appropriately used.
So, I have added a `compilerargs` as an option to pass any of the compiler options to SourceKit.
=> Add compilerargs option to complete command.

CHANGELOG.md, Source/SourceKittenFramework/File.swift
=> Fix bug where documentation inside a function would crash SourceKitten

sourcekitten.xcodeproj/project.pbxproj
I was surprised to find that linking `SourceKittenFramework` to a target caused a build failure with the message `Framework not found Result`.
Both Result and Commandant are not included in the public Cartfile, and appear to be dependencies of `sourcekitten` and not `SourceKittenFramework`. These changes reflect that.
I also removed an old reference to LlamaKit.
Please review! :pray:
=> Link Commandant and Result with sourcekitten, not SourceKittenFramework.

Source/SourceKittenFramework/String+SourceKitten.swift
As discussed in https://github.com/realm/jazzy/issues/347.
Verified that this no longer results in wall of asterisk-style documentation turning into a ul.
=> Consider asterisks when trimming the common prefix of comment blocks.

Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFrameworkTests/Fixtures/Musician.h, Source/SourceKittenFrameworkTests/Fixtures/Musician.json
A pragma mark like the following:
```
#pragma mark - A partially-hyphenated name
```
Was simply showing up as "A partially" in the generated docs. This adjustment to the regex addresses this - though I'm not sure if the hyphen being part of the regex was addressing a different issue.
=> Support hyphenated #pragma mark names.

Source/SourceKittenFramework/String+SourceKitten.swift
It looks as though clang_getCursorExtent() occasionally exceeds the file's length. This fixes https://github.com/realm/jazzy/issues/370
=> fix an out-of-bounds issue when generating pragma marks

CHANGELOG.md, Source/SourceKittenFramework/ObjCDeclarationKind.swift
Should also print more informative errors when encountering unsupported types. Fixes https://github.com/realm/jazzy/issues/374.
=> add support for C/C++ struct & field types

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFramework/SyntaxKind.swift, Source/SourceKittenFramework/SyntaxMap.swift, Source/SourceKittenFrameworkTests/Fixtures/Commandant.json
=> Fix issue where extensions would pick up documentation from previous tokens

CHANGELOG.md, Source/SourceKittenFramework/ObjCDeclarationKind.swift
Fixes https://github.com/realm/jazzy/issues/387.
=> add support for Objective-C ivars

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFrameworkTests/StringTests.swift
Was previously returning full string when all characters matched character set.
=> fix stringByTrimmingTrailingCharactersInSet

sourcekitten.xcodeproj/project.pbxproj
Make `@executable_path/../Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks` first.
`sourcekitten` has direct reference to frameworks contained by SourceKittenFramework.framework.
When some other app distribute those frameworks at `@executable_path/../Frameworks` (regularly `/usr/local/Frameworks`), that will be loaded before contained frameworks.
That case already happened with `swiftlint` and `sourcekitten`.
- "@executable_path/../Frameworks" points relative path from main executable.
When loaded by following:
```
/usr/local/bin/sourcekitten
/usr/local/bin/swiftlint
```
That will be `/usr/local/Frameworks` and is not needed for SourceKittenFramework.
--
```
+ [/usr/local/Frameworks] "@executable_path/../Frameworks" *Removed*
|
+-+ [Frameworks] …
```
=> Fix `LD_RUNPATH_SEARCH_PATHS`

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/String+SourceKitten.swift
`File` is now a `final class` instead of a `struct` and `contents` & `lines` are now marked as `var`. This was done so that mutations to the underlying file on disk can be mirrored in a `File` instance.
=> make `File` `final class` instead of `struct`

Source/SourceKittenFramework/SourceDeclaration.swift, Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFrameworkTests/ClangTranslationUnitTests.swift, Source/SourceKittenFrameworkTests/Fixtures/SuperScript.h, Source/SourceKittenFrameworkTests/Fixtures/SuperScript.json
=> Objective-C marks and non-ASCII characters

Source/sourcekitten/VersionCommand.swift
rather than hardcode in VersionCommand. Same as https://github.com/realm/SwiftLint/pull/224.
=> pull version number from info.plist

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift
By applying this, duration of linting [KeychainAccess](https://github.com/kishikawakatsumi/KeychainAccess/) by SwiftLint is reduced from 27sec to 21sec.
Related: https://github.com/jpsim/SourceKitten/issues/119
=> Optimize `NSRange` conversion

Source/SourceKittenFramework/SyntaxMap.swift
By applying this, linting KeychainAccess by SwiftLint-0.5.1 is reduced from:
```
swiftlint  21.87s user 0.24s system 97% cpu 22.611 total
```
to:
```
swiftlint  17.06s user 0.15s system 97% cpu 17.607 total
```
On Instruments, `commentRangeBeforeOffset()` is reduced from 9931ms:
to 4148ms:
on that test.
=> Optimize `SyntaxMap.commentRangeBeforeOffset(_:)`

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift
Introduce `ByteOffsetCache` for calculating byte offset.
By applying this, linting KeychainAccess by SwiftLint-0.5.1 is reduced from:
```
swiftlint  21.87s user 0.24s system 97% cpu 22.611 total
```
to:
```
swiftlint  16.62s user 0.24s system 97% cpu 17.362 total
```
On Instruments, `NSRangeToByteRange()` is reduced from 6579ms:
to 315ms:
on that test.
=> Optimize `NSString.NSRangeToByteRange(start:length:)`

Source/SourceKittenFramework/SyntaxToken.swift
Contain `SyntaxKind.rawValue` instance instead of `type: String` parameter instance into `SyntaxToken.type`.
This makes comparison faster in some functions. e.g. `commentRangeBeforeOffset(_:)`
Duration of linting KeychainAccess by SwiftLint 0.5.2
before:
```
time swiftlint
…
swiftlint  7.96s user 0.14s system 95% cpu 8.481 total
```
after:
```
swiftlint  5.25s user 0.09s system 93% cpu 5.683 total
```
Now current SwiftLint is faster than 0.4.0 on my test. :smile:
=> Make comparison faster between `SyntaxToken.type` and `SyntaxKind.rawValue`

Source/SourceKittenFramework/String+SourceKitten.swift
The character should be UTF16Index distance as I mentioned in https://github.com/realm/SwiftLint/pull/291#discussion_r48430566
=> Fix `NSString.lineAndCharacterForByteOffset(_:)` returns wrong character

CHANGELOG.md, Source/SourceKittenFramework/Structure.swift
SourceKit `editor.open` response can be shared with `SyntaxMap.init(sourceKitResponse:)` for reducing calls to SourceKit.
=> Add `Structure.init(sourceKitResponse:)`

CHANGELOG.md, Source/SourceKittenFramework/File.swift
By applying this, the duration of `replaceUIDsWithSourceKitStrings(_:)` on linting Carthage is reduced from 3680ms to 1346ms.
from:
to:
=> Change dictionary enumeration in `replaceUIDsWithSourceKitStrings(_:)`

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift
Fix https://github.com/realm/SwiftLint/issues/379
=> Change method of duplicate string in `NSString.CacheContainer`

.gitmodules, Cartfile.private, Cartfile.resolved, Source/sourcekitten/CompleteCommand.swift, Source/sourcekitten/Components.plist, Source/sourcekitten/DocCommand.swift, Source/sourcekitten/StructureCommand.swift, Source/sourcekitten/SyntaxCommand.swift, SourceKitten.xcworkspace/contents.xcworkspacedata, sourcekitten.xcodeproj/project.pbxproj
The syntax is going away in Swift 3, and it's not that hard to do ourselves.
=> removed Curry dependency

.travis.yml, Makefile, Package.swift, Source/SourceKittenFramework/Clang+SourceKitten.swift, Source/SourceKittenFramework/ClangTranslationUnit.swift, Source/SourceKittenFramework/Documentation.swift, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/ObjCDeclarationKind.swift, Source/SourceKittenFramework/Parameter.swift, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SourceDeclaration.swift, Source/SourceKittenFramework/SourceLocation.swift, Source/SourceKittenFramework/SwiftDocs.swift, Source/sourcekitten/VersionCommand.swift, Source/sourcekitten/main.swift, clang_c_module.modulemap
First stab at integrating with OSS Swift, using `sourcekitdInProc` and Swift Package Manager.
This work is necessary to eventually have SourceKitten work on Linux. This is pretty early on in the process, but may be of interest to some (maybe @norio-nomura :smile: ).
=> Support Swift Package Manager

Source/SourceKittenFramework/Request.swift
By applying this, linting Carthage 0.11 by SwiftLint(1fca735):
- Duration is reduced from 22sec to 19sec.
- Persistent Bytes on termination is reduced from 584.61MB to 487.86MB.
Instruments
From:
To:
`String(UTF8String:)`'s back end is `NSString`.
On using `String` as key of Dictionary, it uses `hashValue`.
When `String` is `NSString`, `_stdlib_NSStringNFDHashValue` is always called.
https://github.com/apple/swift/blob/swift-2.2-branch/stdlib%2Fpublic%2Fcore%2FString.swift#L484
That uses `NSString.decomposedStringWithCanonicalMapping` for Unicode Normalization Form D.
https://github.com/apple/swift/blob/swift-2.2-branch/stdlib%2Fpublic%2Fstubs%2FSwiftNativeNSXXXBase.mm.gyb#L118
It seems `decomposedStringWithCanonicalMapping` leaks some memory on above process.
Reduced `CFString (mutable)` …
=> Replace results of `sourcekitd_uid_get_string_ptr()` with enum's rawValue

.travis.yml, Makefile, Package.swift, Source/Clang_C/module.modulemap, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/ObjCDeclarationKind.swift, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SwiftDeclarationKind.swift, Source/SourceKittenFramework/SwiftDocs.swift, clang_c_module.modulemap
- Use new options of Swift Package Manager.
>   -Xcc <flag>        Pass flag through to all compiler instantiations
-Xlinker <flag>    Pass flag through to all linker instantiations
By using them:
- Link `libclang.dylib` in swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a.xctoolchain
- Link `sourcekitd.framework` in swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a.xctoolchain
- Fix build error:
> error: type member may not be named 'Protocol', since it would conflict with the 'foo.Protocol' expression
=> Build with swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a

Source/SourceKittenFramework/Request.swift
Instruments on linting Carthage 0.12,
maximum Persistent Bytes is reduced from 508.49MB to 386.19MB.
From:
To:
Total number of allocation does not increase. (If disposed memory was reused by sourcekitd, it increases.)
Running Time of calling `sourcekitd_response_dispose()` is 282ms:
=> Use `sourcekitd_response_dispose()`

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift
- `locationFromByteOffset` crashed on `byteOffset` points end of string  
`byteOffset` may be out of bounds when sourcekitd points end of string.  
Fix #164
- `byteOffsetFromLocation` crashed on `location` points end of string  
`location` may be out of bounds when `NSRegularExpression` points end of string.
=> Fix crash on offset points end of string

sourcekitten.xcodeproj/project.pbxproj
By applying this, search paths will be following:
- Builded by Xcode.app # Homebrew build will be this.
```sh
@loader_path/Frameworks
/Application/Xcode.app/Toolchains/XcodeDefault.xctoolchain/usr/lib # builded toolchain is first for debugging.
/Application/Xcode.app/Toolchains/XcodeDefault.xctoolchain/usr/lib # duplicated, but no problems occurred by this.
/Application/Xcode-beta.app/Toolchains/XcodeDefault.xctoolchain/usr/lib # This works on Xcode beta image.
```
- Builded by Xcode-beta.app
```sh
@loader_path/Frameworks
/Application/Xcode-beta.app/Toolchains/XcodeDefault.xctoolchain/usr/lib # builded toolchain is first for debugging.
/Application/Xcode.app/Toolchains/XcodeDefault.xctoolchain/usr/lib
/Application/Xcode-beta.app/Toolchains/XcodeDefault.xctoolchain/usr/lib # duplicated,but …
```
=> Add `/Application/Xcode-beta.app/…` to `LD_RUNPATH_SEARCH_PATHS` of SourceKittenFramework

.travis.yml, Makefile, Package.swift, Source/Clang_C/module.modulemap, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SwiftDocs.swift, Source/SourceKittenFrameworkTests/Fixtures/Bicycle.json, Source/SourceKittenFrameworkTests/Fixtures/Bicycle.swift, Source/SourceKittenFrameworkTests/StructureTests.swift
Although it's destructive regarding files on the user's system, this approach allows `swift build` without arguments to succeed. /cc @norio-nomura
=> revert to previous approach for SPM support, requiring no llbuild flags

Makefile, Package.swift, script/spm_bootstrap, script/spm_teardown
also explicitly add antitypical/Result dependency to `Package.swift` due to https://github.com/realm/SwiftLint/pull/516#issuecomment-181734495.
=> move spm_bootstrap and spm_teardown to dedicated scripts

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SwiftDocs.swift, Source/SourceKittenFrameworkTests/SwiftDocsTests.swift, Source/sourcekitten/DocCommand.swift, Source/sourcekitten/main.swift
#166
Notes:
- Use `sourcekitd_set_notification_handler()`.  
`sourcekitd_set_notification_handler()` set the handler to be executed on main thread queue.
So, we vacate main thread to `dispatch_main()`. Without that, SourceKittenFramework waits 10 seconds for SourceKitService restored.
- Add `Request.sendMayThrow()` that may throws `Request.Error`.  
good naming? or change `send()` to throwing error?
- for crashing test, we can use following from apple/swift
```
validation-test/compiler_crashers_fixed/04592-swift-constraints-constraintsystem-simplifyconstraint.swift
validation-test/compiler_crashers_fixed/24947-swift-lexer-leximpl.swift
validation-test/compiler_crashers_fixed/26018-swift-parser-skipsingle.swift
validation-test/compiler_crashers_fixed/26830-swift-printingdiagnosticconsumer-h …
```
=> handle sourcekitd error

Source/SourceKittenFramework/Request.swift
By applying this, the duration of `fromSourceKit(_:)` on linting Carthage 0.13 by SwiftLint is reduced from 2490ms to 1536ms.
from:
to:
Why is capacity 9?
The count of dictionaries are following on above condition:
|count|happen|
|----:|-----:|
|    1|  5043|
|    3|274726|
|    4|     2|
|    5|  1216|
|    6|  1359|
|    7| 28351|
|    8| 38175|
|    9| 20653|
|   10|  4403|
|   11|  2513|
|   12|   255|
|   13|   660|
|   14|   173|
This approach couldn't apply before introducing https://github.com/realm/SwiftLint/pull/487, because of increasing persistent memory.
=> Use `init(minimumCapacity:)` for Dictionary in `fromSourceKit(_:)`

Source/SourceKittenFramework/String+SourceKitten.swift
Fix https://github.com/realm/SwiftLint/issues/315
Based on https://github.com/jpsim/SourceKitten/pull/181#issuecomment-195112226
=> Use `advancedBy(_:limit:)` on potentially passing endIndex

CHANGELOG.md, README.md, Source/sourcekitten/DocCommand.swift
- Fix #174  
Commandant treats `--` as separator that stop parsing named arguments.
- Update Example usage of Doc in README.md  
Insert `--` separator before arguments for `xcodebuild`.
=> Fix "Unrecognized arguments:" error on `doc` command

Makefile
`xcodebuild clean` uses `Debug` configuration without `-configuration`
option, and cleans directories that used by `Debug` configuration. But
`make install` uses `-configuration Release` by scheme of project.  
By this change, `clean` cleans all directories that used by `Debug`,
`Release` and `Test` configurations.
=> Add `-configuration` options to `clean` target in `Makefile`

Source/SourceKittenFramework/SyntaxMap.swift
`isIdentifier` always returned false.
=> Fix ignore identifiers starting with '@'

Package.swift
Because building SWXMLHash-2.3 fails on SPM.
Fixing PR is https://github.com/drmohundro/SWXMLHash/pull/72
SWXMLHash does not have test running SPM on CI, so we should specify stricter version in Package.swift.
=> [SPM] Specify stricter version requirements of SWXMLHash in Package.swift

Tests/SourceKittenFramework/Fixtures/Realm.json
Travis-CI has been updated to Xcode 7.3.1.
https://blog.travis-ci.com/2016-05-05-xcode-731-is-here
=> Update fixture to Xcode 7.3.1

CHANGELOG.md, Source/SourceKittenFramework/library_wrapper.swift
In addition to `DEVELOPER_DIR` environment variable supported by `xcode-select`, `TOOLCHAINS` environment variable is also supported by `xcrun` to selecting alternative toolchains since Xcode 7.3.
SeeAlso: [Alternative Toolchain Support in Xcode Release Notes](https://developer.apple.com/library/mac/releasenotes/DeveloperTools/RN-Xcode/Chapters/xc7_release_notes.html#//apple_ref/doc/uid/TP40001051-CH5-DontLinkElementID_33)
By using `xcrun -find swift` instead of `xcode-select -p`, we can use `DEVELOPER_DIR` and `TOOLCHAINS` environment variables to selecting alternative toolchain for loading SourceKitService.
=> Use `xcrun -find swift` instead of `xcode-select -p`

.gitmodules, CHANGELOG.md, Cartfile, Cartfile.resolved, Package.swift, Source/SourceKittenFramework/Module.swift, Source/sourcekitten/Components.plist, Source/sourcekitten/DocCommand.swift, SourceKitten.xcworkspace/contents.xcworkspacedata, sourcekitten.xcodeproj/project.pbxproj
This adds a way to easily document SPM packages. However, there's a stack overflow issue in the yaml parser library I'm using to parse the Swift Package Manager's build info (behrang/YamlSwift#26), which means that packages that generate a yaml file over ~350 lines has a decent chance of crashing.
```shell
$ git clone https://github.com/qutheory/vapor.git
$ cd vapor
$ swift build
$ echo "$(head -n 384 .build/debug.yaml)" > .build/debug.yaml # workaround for https://github.com/behrang/YamlSwift/issues/26
$ export TOOLCHAIN_DIR=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a.xctoolchain
$ sourcekitten doc --spm-module Vapor > vapor.json
```
You can then run jazzy on the output:
```shell
$ jazzy \
--clean \
--sourcekitten-sourcefile vapor.json \
--author Qutheory \ …
```
=> add way to generate docs for an SPM module

CHANGELOG.md, sourcekitten.xcodeproj/project.pbxproj, sourcekitten.xcodeproj/xcshareddata/xcschemes/SourceKittenFramework.xcscheme, sourcekitten.xcodeproj/xcshareddata/xcschemes/sourcekitten.xcscheme
By applying this, SourceKittenFramework can be used more flexibly from consumer.
- Stop copying libraries to `Frameworks` sub directory in `SourceKittenFramework.framework`
- Remove "Copy Frameworks" build phase from SourceKittenFramework target
- Change SourceKittenFramework target to `EMBEDDED_CONTENT_CONTAINS_SWIFT=NO`
- Add packaging processes for `SourceKittenFramework.framework` to sourcekitten target
- Add a Copy File Build Phase that embedding frameworks into `SourceKittenFramework.framework`
- Add a Shell Script Build Phase that embedding Swift libraries into `SourceKittenFramework.framework`
`swift-stdlib-tool` is called for copying Swift libraries that imitating usage by Xcode.
=> Move embedding frameworks from SourceKittenFramework target to sourcekitten target

sourcekitten.xcodeproj/project.pbxproj
Setting the project's preferred indentation in the project file overrides contributors' defaults, so that no matter their personal preference, they can contribute to SourceKitten with the correct indentation.
=> [.xcodeproj] Specify project indentation

Source/SourceKittenFramework/Request.swift, Source/sourcekitten/IndexCommand.swift, Tests/SourceKittenFramework/SourceKitTests.swift
Just as with `sourcekitten complete`, SourceKit provides much better information when given the correct compiler arguments. Provide a `sourcekitten index --compilerargs` argument, to allow for more correct indexing.
---
This is sort of a work-in-progress, because this removes the automatic mechanism for finding the SDK path. Do consumers of SourceKitten rely on this automatic behavior? Should I provide it as a fallback in case the user didn't specify any `--compilerargs`? Advice from maintainers would be appreciated here. :)
=> [Index] Support --compilerargs

Source/SourceKittenFramework/library_wrapper.swift
Without using `LINUX_SOURCEKIT_LIB_PATH`.
=> Support loading `libsourcekitdInProc.so` placed in default search paths

Makefile
This partially addresses issue #232.
I'm a little confused though as I'm not seeing a `Carthage.zip` file being produced. I do see a `SourceKittenFramework.framework.zip` file though.
=> Added the Yaml and SWXMLHash frameworks to address issue #232.

CHANGELOG.md, Source/SourceKittenFramework/StatementKind.swift, Source/SourceKittenFramework/SwiftDeclarationKind.swift, Source/SourceKittenFramework/SwiftDocKey.swift, Source/SourceKittenFramework/SwiftLangSyntax.swift, Source/SourceKittenFramework/SyntaxKind.swift, sourcekitten.xcodeproj/project.pbxproj
Unite swift lang syntax types with SwiftLangSyntax protocol
Make SwiftDocKey public
=> Swift lang syntax to unite types

Source/sourcekitten/CompleteCommand.swift
Currently the compilerargs are consumed from commandant as a single
quoted string. Because of this, we have to manually split the string at
spaces, which causes issues with arguments, or filepaths with spaces in
them. Instead of doing this we can allow commandant to pass us the
"remaining" arguments trailing the `--` so we can avoid having to split
anything ourselves.
Currently there is a backwards compatibility problem with this, since now doing:
```
sourcekitten complete ... --compilerargs -- ...
```
Will leave `compilerargs` as an unused argument. If we want to make sure we don't break this for current users we could either try to make this command relevant to the new array of arguments, or we could make it a no-op which at least wouldn't throw an error.
Let me know what you think!
=> Change completion's compilerargs to array of strings

CHANGELOG.md, README.md
This updates the CHANGELOG and README to reflect that you no longer pass
`--compilerargs` to the `complete` command.
This is follow up to https://github.com/jpsim/SourceKitten/pull/231
=> Update CHANGELOG and README for compilerargs

CHANGELOG.md, Source/SourceKittenFramework/Info.plist, Source/sourcekitten/Info.plist, Source/sourcekitten/VersionCommand.swift
This is the last release to support Swift 2.2 and Swift 2.3. The next release will require Swift 3.0.
=> Release 0.14.0

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/String+SourceKitten.swift
This makes it compatible with previous behavior and will fix [failing tests](https://travis-ci.org/realm/SwiftLint/jobs/162080744#L761) of https://github.com/realm/SwiftLint/pull/771.
=> Fix `NSString.lines()` generated surplus line when string ended with new line character

script/bootstrap
Fix https://github.com/jpsim/SourceKitten/issues/262
See also: https://github.com/jspahrsummers/objc-build-scripts/issues/13
=> Stop `make` if working tree does not have git repository

Source/SourceKittenFramework/Request.swift
if calling both `initializeSourceKit` and `initializeSourceKitFailable`
=> don't initialize SourceKit twice

Source/SourceKittenFramework/Request.swift
`@available` will be added by separate commit.
=> lowercase Request.Error members to conform to Swift 3 API Design Guidelines

CHANGELOG.md, Source/sourcekitten/CompleteCommand.swift
Adds support for reading the build commands from the `build.yaml` file
closes #270
=> add spm-module to complete command

Source/SourceKittenFramework/Module.swift
Otherwise we get the following failure:
```
fatal error: init(contentsOfFile:usedEncoding:) is not yet implemented: file Foundation/NSString.swift, line 1255
```
=> fix String(contentsOfFile:) on Linux

Source/SourceKittenFramework/Request.swift
This fixes #282.
Now, SourceKitten can be built by Xcode 8.1 GM seed.
=> Add workaround of #282

Tests/SourceKittenFrameworkTests/SourceKitTests.swift
makes Linux tests run in 5s instead of 10s.
=> cache sourcekitStrings to speed up tests

.travis.yml, Cartfile, Cartfile.resolved, Package.swift, Releasing.md, Source/SourceKittenFramework/Module.swift, SourceKitten.podspec
doesn't work yet because YamlSwift hasn't been pushed to CocoaPods Specs in a while (https://github.com/CocoaPods/Specs/tree/master/Specs/Yaml).
=> initial podspec

CHANGELOG.md, Source/SourceKittenFramework/Clang+SourceKitten.swift
I noticed that I made a typo in a code comment of mine and typed `@type` instead of `@param`.
This was interpreted as a comment command. Previously `clang_BlockCommandComment_getCommandName` returned something. With Xcode 8.1 I had a force unwrap.
I noticed the value was actually returned by `clang_InlineCommandComment_getCommandName`
Maybe we should keep the force unwrap instead of the default value (`""`), but do it in `commandName` if it is always expected to return a value ? It could allow us to detect issues like these.
I also updated the fixtures for Xcode 8.1
Thanks
=> some fixes for xcode 8.1

Makefile, Source/SourceKittenFramework/JSONOutput.swift, Source/SourceKittenFramework/Module.swift, sourcekitten.xcodeproj/project.pbxproj
- Add `display_compilation_time` target to `Makefile`
- Reduce build time of two functions
- Set `-Xfrontend -warn-long-function-bodies=200` to `OTHER_SWIFT_FLAGS`
=> Reduce build time

sourcekitten.xcodeproj/project.pbxproj
This is needed in order to be able to link against the framework
when building it through Carthage on Xcode 8.1 (8B62).
=> Set 'use legacy swift language version' to 'no' (== v3.0.1)

CHANGELOG.md, README.md, Source/sourcekitten/YamlRequestCommand.swift, Source/sourcekitten/main.swift, sourcekitten.xcodeproj/project.pbxproj
This command allows you to pass a yaml file that defines a sourcekit
request to be executed.
Fixes https://github.com/jpsim/SourceKitten/issues/312
=> Add yaml-request command

CHANGELOG.md, SourceKittenFramework.podspec
this will break CocoaPods users of the SourceKitten pod, but I don't think there are any consumers other than SwiftLint.
=> rename SourceKitten.podspec to SourceKittenFramework.podspec

CHANGELOG.md, Source/SourceKittenFramework/Clang+SourceKitten.swift, Source/SourceKittenFramework/JSONOutput.swift, Source/SourceKittenFramework/Text.swift
I noticed that the `Text` enum wasn't following the Swift 3 API guidelines for enums. Specifically, I changed `.Para(str1, str2)` to `.para(str1, str2)` and `.Verbatim(str1)` to `.verbatim(str1)`.
=> Make enum case's first letter lowercase

CHANGELOG.md, Source/SourceKittenFramework/Clang+SourceKitten.swift, Source/SourceKittenFramework/Request.swift
Global state dictionaries aren't implicitly thread safe so added locks around access to those variables, so that we avoid crashes in swiftlint and sourcery when using multi-threading.
=> Add locks around shared global state variables

Makefile, sourcekitten.xcodeproj/project.pbxproj
- Stop using `swift-stdlib-tool`  
Xcode 8.3 beta 2 no longer includes `swift-stdlib-tool`.
So, we need changes:
- Remove “Embed Swift libraries into SourceKittenFramework.framework” build phase that using `swift-stdlib-tool`
- Add a job to `installables` target that moves Swift Standard Libraries from `sourcekitten.app` bundle to `SourceKittenFramework.framework`
- Change so that `SourceKitten.pkg` does not include `/Applications`
The former change is also needed in `SwiftLint` on Xcode 8.3 beta 2.
=> Change packaging

Source/SourceKittenFramework/Clang+SourceKitten.swift, Source/SourceKittenFramework/Documentation.swift, Source/SourceKittenFramework/Parameter.swift, Source/SourceKittenFramework/SourceDeclaration.swift, Source/SourceKittenFramework/SourceLocation.swift
I'm making a command line tool to generate documentation from Objective-C headers. (Similar to jazzy but written in swift). So I embed `SourceKittenFramework` in my app and use `ClangTranslationUnit` to parse headers and get `SourceDeclaration` instances. If those properties can not be access outside the framework, it seems I must transform `SourceDeclaration` instances to JSON then parse JSON to Dictionary then map to my models.
By mark those properties public, application can directly map information from `SourceDeclaration` to their models. Rather than parse the JSON output from `ClangTranslationUnit`.
=> Expose properties of `SourceDeclaration` which can be used by `SourceKittenFramework` users.

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
When the string ended with extended grapheme clusters, the method
crashed because of the force-unwrapping. This refactoring adds support
for handling extended grapheme clusters.
This fixes #350
=> Fix the trimming of trailing characters.

Source/SourceKittenFramework/ClangTranslationUnit.swift
Swift 4.0 produces error for this.
```
…/Source/SourceKittenFramework/ClangTranslationUnit.swift:23:33: error: redundant conformance constraint 'U': 'Hashable'
fileprivate func grouped<U: Hashable>(by transform: (Iterator.Element) -> U) -> [U: [Iterator.Element]] {
^
…/Source/SourceKittenFramework/ClangTranslationUnit.swift:23:85: note: conformance constraint 'U': 'Hashable' inferred from type here
fileprivate func grouped<U: Hashable>(by transform: (Iterator.Element) -> U) -> [U: [Iterator.Element]] {
^
```
=> Remove redundant conformance constraint 'U': 'Hashable'

Cartfile.resolved, Makefile, Package.swift, Tests/SourceKittenFrameworkTests/ModuleTests.swift, Tests/SourceKittenFrameworkTests/SwiftDocsTests.swift
tests crash with Swift 3.1.1 on Linux:
Fixes #379
=> Fix tests crash with Swift 3.1.1 on Linux

Source/sourcekitten/CompleteCommand.swift, Source/sourcekitten/DocCommand.swift, Source/sourcekitten/FormatCommand.swift, Source/sourcekitten/IndexCommand.swift, Source/sourcekitten/StructureCommand.swift, Source/sourcekitten/SyntaxCommand.swift, Source/sourcekitten/VersionCommand.swift, Source/sourcekitten/YamlRequestCommand.swift
Is this affected by [SE-0110](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md)?
Extracted from https://github.com/jpsim/SourceKitten/pull/377 which can be applied without passing test on https://github.com/jpsim/SourceKitten/pull/377.
=> Chang to explicitly pass `()` to `Result.success()`

Source/SourceKittenFramework/String+SourceKitten.swift
https://github.com/apple/swift-evolution/blob/master/proposals/0163-string-revision-1.md#source-compatibility
Extracted from #377 which can be applied without passing test on #377.
=> 'subscript' returning `String` will be obsoleted in Swift 4

.travis.yml, Makefile, Package.swift, Source/SourceKittenFramework/LinuxCompatibility.swift, Source/SourceKittenFramework/Module.swift, Tests/SourceKittenFrameworkTests/CodeCompletionTests.swift, Tests/SourceKittenFrameworkTests/Fixtures/SimpleCodeCompletion.swift4.json
- Add travis job with `swift-4.0-DEVELOPMENT-SNAPSHOT-2017-05-11-a` on Linux
- It can't be built with `swift-4.0-DEVELOPMENT-SNAPSHOT-2017-05-11-a` on macOS since compiler crashes. [SR-4863](https://bugs.swift.org/browse/SR-4863)
- Building with SwiftPM requires Swift 3.1 or later.
- Building by SwiftPM with Swift 3.0.2 should be able to resurrect if [SR-4848](https://bugs.swift.org/browse/SR-4848) would be fixed.
=> Swift 4.0 on Linux

Source/SourceKittenFramework/String+SourceKitten.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
See https://github.com/realm/SwiftLint/issues/1006
=> Fix crash in lineAndCharacter(forByteOffset:)

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFramework/SwiftDocKey.swift, Tests/SourceKittenFrameworkTests/Fixtures/Extension.json, Tests/SourceKittenFrameworkTests/Fixtures/Extension.swift, Tests/SourceKittenFrameworkTests/Fixtures/LinuxExtension.json
From realm/jazzy#333.  Given:
```swift
class Outer {
class Inner {
}
}
extension Outer.Inner {
}
```
...sourcekitten associates the extension with `Outer` -- ie. `key.name` and `key.usr` match `Outer`.  This happens because of the `source.request.cursorinfo` made for the extension against the `Outer.Inner` name: SourceKit interprets this as a request for info about the `Outer` type and diligently returns it.
This PR handles declaration names containing dots and advances the offset of the cursorinfo to the last portion, which is the actual type of the extension.
=> Fix extensions of nested types

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift
Speeds up SwiftLint linting itself on Linux by ~13x (15s vs 3m23s).
=> Cache NSString.CacheContainer on Linux

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
The line/column information normally takes tab width into account. The `W` in the following example would be reported to be at character 9 (for a tab width of 4), but currently it is reported as 6.
```
Hello\tWorld!
```
I picked 1 as a default value to make this a non-breaking change, but as stated above `4` is probably more reasonable. Let me know how you feel about the change in general and what your preference on the default value is.
P.S. This is in preparation of a PR I wanted to do on SwiftLint, to make the vertical parameter alignment rule handle tabs better.
=> Add tabWidth parameter (default: 1) for lineAndCharacter

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
For something like:
```swift
class C {
func ff(a: String,
b: String) {
}
}
```
...make sure the `key.parsed_declaration` looks like:
```swift
func ff(a: String,
b: String)
```
...instead of (current):
```swift
func ff(a: String,
b: String)
```
From eg. realm/jazzy#836.
=> Keep user alignment of multi-line Swift declarations

.circleci/config.yml, Cartfile.resolved
~~This is a demonstration that SWXMLHash 4.2.4 is broken.~~
This is required for `pod lib lint` on Xcode 9.1.
=> Update SWXMLHash to 4.2.5

Tests/SourceKittenFrameworkTests/ModuleTests.swift
By applying this, intermediate files built during the current test session will be maintained before and after `testSourceKittenFrameworkDocsAreValidJSON()` execution, and the time to test re-execution will be shorter.
=> Use `-derivedDataPath` on `testSourceKittenFrameworkDocsAreValidJSON`

CHANGELOG.md, Source/SourceKittenFramework/Clang+SourceKitten.swift, Tests/SourceKittenFrameworkTests/Fixtures/Realm@swift-3.2.json
Spotted by a patient jazzy user in realm/jazzy#910.  When SourceKit produces the full_as_xml as part of a cursorinfo request for a decl *imported from ObjC*, it forgets to XML-escape the ‘Declaration’.  SourceKitten had a fix for ‘&’ but not ‘<’ ‘>’ (generics) - causes truncation of the Swift decl.
This PR changes SourceKitten to always use the annotated_declaration_xml instead of trying to work around the Swift bug -- this XML is generated using different code that has always been escaped properly.  For ObjC, the contents of the two declarations are identical.
Testcase change show Realm ObjC was suffering from this -- various generic declarations missing pieces in Swift.
=> Fix generic Swift declaration generation from ObjC

CHANGELOG.md, Source/SourceKittenFramework/Clang+SourceKitten.swift, Source/SourceKittenFramework/File.swift, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/Structure.swift, Source/SourceKittenFramework/SwiftDocs.swift, Source/SourceKittenFramework/SyntaxMap.swift, Source/sourcekitten/CompleteCommand.swift, Source/sourcekitten/Errors.swift, Source/sourcekitten/FormatCommand.swift, Source/sourcekitten/IndexCommand.swift, Source/sourcekitten/StructureCommand.swift, Source/sourcekitten/SyntaxCommand.swift, Source/sourcekitten/YamlRequestCommand.swift, Tests/SourceKittenFrameworkTests/CodeCompletionTests.swift, Tests/SourceKittenFrameworkTests/DocInfoTests.swift, Tests/SourceKittenFrameworkTests/FileTests.swift, Tests/SourceKittenFrameworkTests/OffsetMapTests.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift, Tests/SourceKittenFrameworkTests/StringTests.swift, Tests/SourceKittenFrameworkTests/StructureTests.swift, Tests/SourceKittenFrameworkTests/SyntaxTests.swift
~~Use `Request.failableSend()` instead of `Request.send()`~~
Change `Request.send()` to `throws`
Some APIs changed to `throws`:
* `File.format(trimmingTrailingWhitespace:useTabs:indentWidth:) throws`
* `Structure.init(file:) throws`
* `SyntaxMap.init(file:) throws`
=> Deprecate `Request.failableSend()`

Tests/SourceKittenFrameworkTests/SwiftDocsTests.swift
- Add swift-4.1, 3.3, 4.0.3 and 3.2.3 to `versionedExpectedFilename(for:)`
- Print diff on comparing JSON
- Add `appendFixturesForNewSwiftVersion` operation to `compareJSONString()`  
This will support appending fixtures for new Swift version.
=> Improve comparing JSON

Source/SourceKittenFramework/Module.swift, Tests/SourceKittenFrameworkTests/Fixtures/Commandant@swift-3.2.json
The order of `sourcefiles` are different between SPM and Xcode.
- Sorted alphabetically on SPM
- In the order described in Compile Sources build phase within Xcode project
These affect the differences in fixtures generated by `testCommandantDocs()` and `testCommandantDocsSPM()`.
This change minimizes that difference.
=> Sort `sourcefiles` on producing `Module.docs`

Source/SourceKittenFramework/SwiftDocKey.swift
https://github.com/apple/swift/blob/master/tools/SourceKit/docs/Protocol.md
> <key.substructure>:   (dictionary)  // Contains an array of dictionaries ...
=> [SwiftDocKey] Make Substructure type description more explicit

Tests/SourceKittenFrameworkTests/ModuleTests.swift
Since the directory to check out Commandant differs depending on the version of Swift, if you run `swift build` with multiple versions of Swift without `swift package reset`, there may be multiple checked out Commandant directories.
That may cause `testCommandantDocsSPM()` to fail.
This change prevents that failure by getting Commandant's directory used in the test with `swift package show-dependencies`.
=> Use `swift package show-dependencies` for searching Commandant

CHANGELOG.md, Source/SourceKittenFramework/library_wrapper.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift
These commits add two new search strategies for Linux to the two existing strategies.
The first one checks to see if swiftenv is configured; if so, it uses `swiftenv prefix` to find the lib directory of the current active Swift environment - which is likely what the user is expecting.
The second one checks to see if `swift` is on `$PATH`; if it is, it's likely that the user is building their own toolchain and that's probably the libsourcekitdInProc.so the user is expecting.
This required a little duplication in SourceKitTests.swift that I'm happy to refactor out.
=> Improved searching for libsourcekitdInProc.so on Linux for library_wrapper.swift

Source/SourceKittenFramework/Xcode.swift
I'm still following up on Foundation but it really looks like `task.launch()` is supposed to do something exceptional - currently on Linux there's no way to tell your launch failed.
https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/Process.swift#L409 _should_ yield a fatalError.
I started https://forums.swift.org/t/unexpected-inconsistent-behavior-in-process-launch/9398 to discuss this because if that's fixed, code like this will start breaking, and from a reading of `posix_spawn` it's not entirely clear what the behavior should be.
Regardless of the decision made with Foundation, this change is safe - `/usr/bin/xcrun` will never exist on Linux, so there's no point trying to launch it. This unblocks users/tests on non-Ubuntu platforms and has no effect on existing …
=> Do not attempt to run `/usr/bin/xcrun` on Linux

CHANGELOG.md, Source/sourcekitten/IndexCommand.swift
=> Change to use `Argument` instead of `Option` on `IndexCommand.Options.compilerargs`

Source/SourceKittenFramework/library_wrapper.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift
Should we use `-warnings-as-errors` on Linux CI?
=> 'flatMap' is deprecated: renamed to 'compactMap(_:)'

Package.swift
Since 0.19.1 has `.upToNextMinor(from: "0.5.0")` as requirements, SwiftLint can't update Yams to 0.6.0 without updating SourceKitten.
This change will avoid such situation in future.
=> Loosen version requirement of Yams in `Package.swift`

CHANGELOG.md, Source/SourceKittenFramework/SwiftDeclarationAttributeKind.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift, sourcekitten.xcodeproj/project.pbxproj
Implementing issue https://github.com/jpsim/SourceKitten/issues/504
=> Introducing SwiftDeclarationAttributeKind

CHANGELOG.md, Source/SourceKittenFramework/File.swift
- Fix https://github.com/realm/SwiftLint/issues/2089
- Remove `File.lines:setter`
=> Add exclusive control to `File.contents` and `File.lines`

Tests/SourceKittenFrameworkTests/SwiftDocsTests.swift
Confirmed that updating fixtures is unnecessary on `swift-4.1-DEVELOPMENT-SNAPSHOT-2018-05-12-a`.
=> Add `swift-4.1.2` to `versionedExpectedFilename(for:)`

Tests/SourceKittenFrameworkTests/ModuleTests.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift, sourcekitten.xcodeproj/xcshareddata/xcschemes/sourcekitten.xcscheme
- Enable test parallelization option of `SourceKittenFrameworkTests` in `sourcekitten` scheme on Xcode 10
- Merge `testSourceKittenFrameworkDocsAreValidJSON` into `testLibraryWrappersAreUpToDate`  
Since both of `ModuleTests.testSourceKittenFrameworkDocsAreValidJSON()` and `SourceKitTests.testLibraryWrappersAreUpToDate()` used same build configuration `sourcekittenXcodebuildArguments`, one of `xcodebuild` instances was failing with error when test parallelization is enabled.
This changes avoid that.
=> Enable test parallelization on Xcode 10

CHANGELOG.md, Source/SourceKittenFramework/JSONOutput.swift, Source/SourceKittenFramework/SourceDeclaration.swift, Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFramework/SwiftDocKey.swift, Tests/SourceKittenFrameworkTests/Fixtures/Musician.h, Tests/SourceKittenFrameworkTests/Fixtures/Musician.json
Example annotation:
```
- (void)someMethod __attribute__((annotate("This is a custom annotation.")));
```
Will appear in the output as part of a new `annotations` field as `["This is a custom annotation."]`.
=> Add support for C-language annotations.

.circleci/config.yml
This reduces the `swiftlint lint` step from 35-120 seconds to few seconds.
=> [CircleCI] Avoid auto updating Homebrew on installing `swiftlint`

CHANGELOG.md, Source/SourceKittenFramework/ClangTranslationUnit.swift, Source/SourceKittenFramework/Module.swift, Source/SourceKittenFramework/Xcode.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift, sourcekitten.xcodeproj/xcshareddata/xcschemes/sourcekitten.xcscheme
Since Xcode’s New Build System uses `llbuild`, compiler arguments for `Module` can be retrieved from manifest of `llbuild` instead of parsing `xcodebuild`’s output. Until this changes, the `clean` action was used for `xcodebuild` to ensure compiler arguments, but it is not necessary when using the New Build System.
=> Avoid `clean` on running `xcodebuild` if New Build System is used.

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
when using unicode characters. Reported in realm/SwiftLint#2276
=> Fix crash in NSString.location(fromByteOffset:)

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFramework/library_wrapper.swift
A “.swift”-suffixed directory in `xcodebuild` arguments is no longer detected as a Swift file.
Fixes #574.
=> Fix misidentification of .swift-suffixed directory as a Swift file

Makefile
This is required on building with Xcode 10.2, because Xcode 10.2’s toolchain does not have `usr/lib/swift_static` directory.
=> [Makefile] Avoid using `-Xswiftc -static-stdlib` if toolchain does not have `usr/lib/swift_static` directory

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift, Source/SourceKittenFramework/Xcode.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
realm/jazzy#1049 shows that if the source paths include characters (other than space) that the shell needs escaping like quotes, then xcodebuild does that escaping in its output but sourcekitten fails because the .swift pathnames still contain the escaping backslashes.
This PR undoes the backslash escaping as part of parsing the Xcode arguments.
(I couldn't find a library function for this or a regex solution that wasn't extremely opaque, improvements v welcome...  the approach here goes wrong if there were arguments that are themselves quoted strings containing backslashes but we'd be broken there already on spaces so I guess they don't exist...)
=> Undo shell escapes from xcodebuild

Source/SourceKittenFramework/library_wrapper.swift
With 0.22.0, if I run sourcekitten, I'll get this printed:
```
/usr/bin/which: no swiftenv in (/home/ryan/bin:/var/lib/bluecap/exports/bin:/home/ryan/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/home/ryan/.cargopak/bin:/home/ryan/Android/Sdk/platform-tools:/home/ryan/.local/bin:/home/ryan/.cargo/bin:/home/ryan/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```
even if/when the command successfully finds the sourcekit library.
=> Silence errors due to which failing to find swiftenv

CHANGELOG.md, Source/SourceKittenFramework/Xcode.swift
When the new build system `manifest.xcbuild` file is used to figure out compiler args, the path to `swiftc` itself gets included.
This is different to old build system / SPM, and although it is (apparently) ignored by `cursorinfo` it causes problems with other requests (`docinfo` happens to be the one I'm working with).
This PR aligns the new-build-system args finder with the other two kinds.
=> Don't pass swiftc to sourcekit with new build system

CHANGELOG.md, Source/SourceKittenFramework/Xcode.swift
Found via realm/jazzy#1057.
`xcodebuild` in 10.2 requires an additional signing-related flag to skip signing without failing when using the new build system.
The `XcodeBuild.cleanBuild()` path is unreachable on new build system if all is well but we get there if user has wrong settings (etc).
edit: tested this on matrix of Xcode 10.1/10.2, new/old build system, project needs/doesn't need signing.
=> Fix clean xcodebuild with Xcode 10.2 and new build system

CHANGELOG.md, Source/SourceKittenFramework/Module.swift, Source/SourceKittenFramework/Xcode.swift, Source/SourceKittenFramework/XcodeBuildSetting.swift, Tests/SourceKittenFrameworkTests/Fixtures/CommandantResultTVOS@swift-4.2.json, Tests/SourceKittenFrameworkTests/ModuleTests.swift, sourcekitten.xcodeproj/project.pbxproj
Carried over from https://github.com/jpsim/SourceKitten/pull/578 which I accidentally closed somehow 🤦‍♂️.
---
This PR introduces `XcodeBuildSetting`—a safer, faster alternative to using regex—& improves the module name inference in `Module`. 
The prior solution would fail to build a platform-suffixed target, like `'Result-tvOS'`, due to `moduleName(fromArguments:)`'s assumption that the target/scheme name will be equivalent to the module name. The new implementation will read the module name from the build settings. It will use, in order of priority, the value of the user-defined key `"SWIFT_MODULE_NAME"` & then `"PRODUCT_MODULE_NAME"`. If this fails for whatever reason, it will use `moduleName(fromArguments:)`.
=> Improve Module Name Inference

CHANGELOG.md, Source/SourceKittenFramework/File.swift, Tests/SourceKittenFrameworkTests/Fixtures/Commandant@swift-4.2.json, Tests/SourceKittenFrameworkTests/Fixtures/Commandant@swift-5.0.json, Tests/SourceKittenFrameworkTests/Fixtures/CommandantResultTVOS@swift-4.2.json, Tests/SourceKittenFrameworkTests/Fixtures/CommandantResultTVOS@swift-5.0.json, Tests/SourceKittenFrameworkTests/Fixtures/CommandantSPM@swift-4.2.json, Tests/SourceKittenFrameworkTests/Fixtures/CommandantSPM@swift-5.0.json, Tests/SourceKittenFrameworkTests/Fixtures/Extension@swift-4.2.json, Tests/SourceKittenFrameworkTests/Fixtures/Extension@swift-5.0.json, Tests/SourceKittenFrameworkTests/Fixtures/LinuxBicycle@swift-4.2.json, Tests/SourceKittenFrameworkTests/Fixtures/LinuxBicycle@swift-5.0.json, Tests/SourceKittenFrameworkTests/Fixtures/LinuxCommandantSPM@swift-4.2.json, Tests/SourceKittenFrameworkTests/Fixtures/LinuxCommandantSPM@swift-5.0.json
This populates `parsed_declaration` for `extension` declarations.
This is the simplest way I've found to get the actual extension declaration along with any constraints - the cursor-info declarations give us info about the _extended_ type.
Peering back through file history these may have been originally excluded due to overwriting fields from doc-structure with incorrect ones from cursor-info, which was since fixed.  Or there could have been SourceKit bugs now fixed.  At any rate, this version looks to work well for the fixtures here and various jazzy projects.
=> Include parsed extension declarations in docs

CHANGELOG.md, Source/SourceKittenFramework/File+Hashable.swift, sourcekitten.xcodeproj/project.pbxproj
Implemented pulled verbatim from https://github.com/realm/SwiftLint/pull/2714, since it was correct right off the bat!
=> Make `File` conform to `Equatable` and `Hashable`

CHANGELOG.md, Source/SourceKittenFramework/Module.swift, Tests/SourceKittenFrameworkTests/ModuleTests.swift
It is required for Xcode 11, because Xcode 11 does not use `SRCROOT` as current directory on executing tests
in `Package.swift`.
I got an answer from apple that this Xcode 11's behavior is expected. (FB6115942)
=> Change `Module.init?(spmName:)` to `Module.init?(spmName:inPath:)`

CHANGELOG.md, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SourceKitObject.swift, Source/SourceKittenFramework/UID.swift, Source/SourceKittenFramework/UIDRepresentable.swift, sourcekitten.xcodeproj/project.pbxproj
I moved all code that interacts with `sourcekitd_object_t` into `SourceKitObject.swift`. This way it's easier to manage the lifecycle of `sourcekitd_object_t` pointers.
Relates to: https://github.com/realm/SwiftLint/issues/2812
I think this could be simplified/improved even more by exposing SourceKitObject as a typealias for `[String: SourceKitObjectConvertible]`. Then when we make the request, converting to `sourcekitd_object_t` pointers, making the request, then freeing the pointers. This means that for the most part you're only working with swift types and the `sourcekitd_object_t` lifecycle is greatly shorted and simplified.
=> Refactor SourceKitObject to release memory

Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SwiftDocKey.swift, Source/SourceKittenFramework/XcodeBuildSetting.swift, Source/SourceKittenFramework/library_wrapper.swift, Source/SourceKittenFramework/library_wrapper_CXString.swift, Source/SourceKittenFramework/library_wrapper_Documentation.swift, Source/SourceKittenFramework/library_wrapper_Index.swift, Source/SourceKittenFramework/library_wrapper_sourcekitd.swift
Also restructure `library_wrapper.swift` to only expose the declarations needed on Darwin and Linux to that platform.
=> Remove unused declarations

CHANGELOG.md, Source/SourceKittenFramework/Module.swift, Source/sourcekitten/DocCommand.swift, Tests/SourceKittenFrameworkTests/ModuleTests.swift
This adds an `--spm` option to auto-detect a sensible module name.
This is in aid of bringing spm support up to parity with xcodebuild in jazzy -- wanted to get some feedback before going further.
If the idea and this piece look OK then the next is to add a `swift build` call somewhere along the way to make sure the build DB is present and up to date, as we do with xcodebuild.  I think it makes sense to add this call to sourcekitten (vs. jazzy) to preserve the existing layering & keep sourcekitten self-consistent?
Jazzy prototype with this in realm/jazzy#1089
=> Autodetect SPM module name for docs generation

CHANGELOG.md, Source/SourceKittenFramework/Module.swift, Source/SourceKittenFramework/String+SourceKitten.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
This adds Xcode11 support to docs generation, reading the new response file to figure out the source files.
It turns out SourceKit doesn't support response files ("_filename_ is not part of the input files" error) so we expand them before passing on.
Added a quick test that could go away when the SourceKitten tests pass with Xcode11; jazzy specs all build fine with this change.
=> Support response files in Swift compiler arguments

CHANGELOG.md, Source/SourceKittenFramework/Exec.swift, Source/SourceKittenFramework/Module.swift, Source/SourceKittenFramework/Xcode.swift, Source/SourceKittenFramework/library_wrapper.swift, Source/sourcekitten/DocCommand.swift, Tests/SourceKittenFrameworkTests/ModuleTests.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift, Tests/SourceKittenFrameworkTests/SwiftDocsTests.swift, sourcekitten.xcodeproj/project.pbxproj
Final part of jazzy+SPM support: this runs `swift build` as part of generating docs for SPM modules.  This makes sure that the build manifest (a) exists and (b) is consistent with the latest changes to the source code, same as Xcode path.  (No need to do a `clean` so is v. cheap if the package has already been built.)
First commit is a pure refactor of all the popen-ish code because I couldn't stand duplicating it again.  Accounts for most of the changed LOC.
Second commit adds a `Module` initializer that runs `swift build` before going to SourceKit.
I tentatively kept the existing SPM initializer to keep semantics for existing users (SourceDocs uses it, didn't look further).
=> Add package build step to SPM docs generation

CHANGELOG.md, Source/SourceKittenFramework/String+SourceKitten.swift, Tests/SourceKittenFrameworkTests/StringTests.swift
The Xcode 11 Swift response files contain backslash escapes for spaces etc.  I'd somehow convinced myself they didn't.
Addresses realm/jazzy#1108.
_Technically_ unescaped spaces are supposed to delimit separate arguments, but Xcode doesn't use this today.  We would need to reimplement [this code](https://github.com/apple/swift-llvm/blob/c5340df2d1aed4cd16fb43e1ce11139a407f2055/lib/Support/CommandLine.cpp#L702) -- I think this version is OK for now.
=> Fix response file parsing for escaped characters

Source/SourceKittenFramework/Clang+SourceKitten.swift, Tests/SourceKittenFrameworkTests/Fixtures/Musician.h, Tests/SourceKittenFrameworkTests/Fixtures/Musician.json
In the case that there are raw HTML tags in content, don't blow up, just pass along the content. Things like Swift generated headers contain HTML quite a bit and the error is pretty ambiguous when this fatals.
Fixes #409 / realm/jazzy#976
=> Allow inline html tags in ObjC doc comments

Source/SourceKittenFramework/Clang+SourceKitten.swift, Tests/SourceKittenFrameworkTests/ClangTranslationUnitTests.swift, Tests/SourceKittenFrameworkTests/Fixtures/CodeFormatting.h, Tests/SourceKittenFrameworkTests/Fixtures/CodeFormatting.json
=> Add support for code formatting in Obj-C header comments

CHANGELOG.md, Source/SourceKittenFramework/Module.swift, Source/SourceKittenFramework/Xcode.swift
Fixes #643. (and probably the inexplicable stuff in realm/jazzy#1087)
This has happened since SourceKitten started running `xcodebuild` multiple times with the 'new' build system.  If the initial build fails then SourceKitten doesn't notice and can proceed to generate docs from the build manifest that the failing `xcodebuild` invocation has just created.
There are two things that can happen next:
1. Empty docs are generated.  This means `xcodebuild` has created the build manifest but _not_ populated the Swift response file.  Well proven in #643.
2. Partially complete docs are generated.  This time the response file is there, but there is probably a compilation error in one of the files meaning the SourceKit cursorinfo will silently fail in some places.  I don't _think_ this is a feature? …
=> Stop and report an error if xcodebuild fails

Source/SourceKittenFramework/CodeCompletionItem.swift
With Swift 5.2 this code produced this warning:
```
Source/SourceKittenFramework/CodeCompletionItem.swift:65:65: error: cast from 'SourceKitRepresentable?' to unrelated type 'CodeCompletionItem.NumBytesInt' (aka 'Int') always fails
numBytesToErase: dict["key.num_bytes_to_erase"] as? NumBytesInt)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~~~~~~~~~~
```
Switching this to use `Int64` as it does on Darwin seems to fix this.
I've left the conditional here for older versions of Swift on Linux
https://github.com/jpsim/sourcekitten/commit/61b3edf36f4042b7069d9deaa41df5b758542d91
=> Fix type on Linux with Swift 5.2

CHANGELOG.md, Source/SourceKittenFramework/ClangTranslationUnit.swift, Source/SourceKittenFramework/Module.swift, Source/SourceKittenFramework/Xcode.swift
Continuation of / fixup for #646, fixes realm/jazzy#1183.
If we're going to stop when `xcodebuild` fails we must make sure to set the vars that
disable code signing otherwise it will just fail for signing-related reasons and never
make it to the 'clean build' part.
Build with this change makes the projects from the jazzy issue build cleanly.
=> Bypass codesign when building Xcode projects

Source/SourceKittenFramework/SwiftDocs.swift
Include Glibc to support stderr in order to compile successfully in a Linux environment.
=> Include Glibc to support stderr.

Package.resolved, Package.swift
I would like to upgrade the ArgumentParser dependency to 0.4+ so I can use the latest version in my project 🙂
=> Bump ArgumentParser from 0.3.1 to 0.4.1

CHANGELOG.md, Source/SourceKittenFramework/SwiftDocKey.swift
#703 continued, GitHub too clever for me with combo of conflicts + first-time contributor.
=> Add `key.attributes` and `key.attribute` enum cases to SwiftDocKey

Source/SourceKittenFramework/JSONOutput.swift, Source/sourcekitten/Complete.swift
Since JSON-formatting of code completion results can take a lot of time in some cases, additional format options can be passed to the sourcekitten.
Two additional options added:
- `prettified` - whether JSON results should be user-friendly prettified
- `sorted-keys` - whether the keys in JSON should be sorted keys
This fixes #710
=> Add sourcekitten completion results formatting options

CHANGELOG.md, Source/SourceKittenFramework/File.swift
Swift 5.6 SourceKit has changed the `source.lang.swift.decl.enumcase` attributes in a way that crashes `sourcekitten doc` on any code with enum cases.
Recall that `enumcase` is the wrapper around a set of `enumelement`s with actual info.  In earlier Swift, `enumcase` had `key.nameoffset` and `key.namelength` fields but these were always 0.  In Swift 5.6 they're entirely gone.
A net gain for sourcekitten because it turns out we were doing useless cursorinfo queries.
This patch is enough to make jazzy work normally, not found any other breakage.
=> Fix docs generation with Swift 5.6

CHANGELOG.md, README.md, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SourceKittenConfiguration.swift, Source/SourceKittenFramework/library_wrapper.swift, Source/SourceKittenFramework/library_wrapper_SourceKit.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift
There are two versions of sourcekitd that come with Xcode:
- `sourcekitd.framework`, which uses XPC to connect to the sourcekit daemon and parse swift files out-of-process.
- `sourcekitdInProc.framework`, which does the parsing in-process.
SourceKitten uses the XPC version on macOS. However, there may be cases, when the in-process version might be preferred. So this PR adds the possibility to configure this using the following environment variable:
USE_INPROC_SOURCEKIT=YES
Specifically, this will be needed to support running SourceKitten in Swift Package Manager build tool plugins. It is a new feature ([SE-0303](https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md)) in Swift 5.6, that allows Swift packages to execute custom build commands …
=> Add InProc Option for Sourcekitd

Source/BUILD, Source/Clang_C/Clang_C.modulemap, Source/SourceKit/SourceKit.modulemap, Source/SourceKittenFramework/Request.swift, Source/SourceKittenFramework/SwiftDocs.swift, Source/SourceKittenFramework/library_wrapper_Clang_C.swift
By moving the `objc_library` targets to be `cc_library` and `swift_c_module`, which is fine because these are header-only libraries.
=> Support compiling with Bazel on Linux

Source/BUILD
To avoid `-Wempty-translation-unit` errors such as this one:
```
Source/SourceKit/SourceKit.c:1:1: error: ISO C requires a translation unit to contain at least one declaration [-Werror,-Wempty-translation-unit]
```
=> [Bazel] Remove sources from cc libraries

Source/SourceKittenFramework/SourceKitObject.swift
`String.init(bytesNoCopy:...)` was deprecated in macOS 13: https://developer.apple.com/documentation/swift/string/init(bytesnocopy:length:encoding:freewhendone:)
Further discussion here: https://forums.swift.org/t/does-string-bytesnocopy-copy-bytes/51643/11
=> Fix deprecation warning

CHANGELOG.md, Source/SourceKittenFramework/Xcode.swift
Docs generation fails at cursor-info on Xcode 14 because of a new flag:
It turns out that sourcekitten is already filtering out a suspiciously-similarly named flag so I've just added this new one.  Jazzy etc. work fine with this change.
=> Filter out unsupported Swift 5.7 flags

.gitattributes
The fixture data is expected to be in Unix line endings in order to
match the test expectations.  This is important to ensure that the files
are properly checked out on Windows to support executing the tests.
=> gitattributes: ensure that we use Unix line endings for fixtures

Tests/SourceKittenFrameworkTests/ModuleTests.swift
Xcode is only available on the macOS platform.  Rather than enumerating all the other OSes, simply limit the test cases to that platform.
=> Tests: disable Xcode tests on non-macOS platforms

CHANGELOG.md, Source/SourceKittenFramework/SwiftDeclarationAttributeKind.swift, Source/SourceKittenFramework/SwiftDeclarationKind.swift, Source/SourceKittenFramework/SyntaxKind.swift, Tests/SourceKittenFrameworkTests/Fixtures/Commandant@swift-5.8.json, Tests/SourceKittenFrameworkTests/Fixtures/CommandantSPM@swift-5.8.json, Tests/SourceKittenFrameworkTests/ModuleTests.swift, Tests/SourceKittenFrameworkTests/SourceKitTests.swift, Tests/SourceKittenFrameworkTests/StructureTests.swift, Tests/SourceKittenFrameworkTests/SwiftDocsTests.swift
- Add type hints to resolve Swift 5.8 warnings
- Add 5.8 test fixtures
- Adjust compiler versions in tests
- Add `source.lang.swift.syntaxtype.operator` syntax kind
- Add `source.lang.swift.decl.macro` declaration kind
- Add new declaration attribute kinds
=> Add Swift 5.8 Support

Source/SourceKittenFramework/WindowsError.swift, Source/SourceKittenFramework/library_wrapper.swift
This adds Windows specific handling for dynamic symbol resolution into a library.  The `dlopen` and `dlsym` APIs are not portable as they are part of POSIX rather than the C standard.  Use the Windows equivalents of `LoadLibraryW` and `GetProcAddress`.
TODO: this requires further refinement to detect the Swift toolchain installation.
=> SourceKittenFramework: largely port library loading for Windows

Tests/SourceKittenFrameworkTests/SwiftDocsTests.swift
Ensure that we normalise the path when we substitute the path into the results to properly remove the basename of the fixture.
=> Tests: normalise the fixtures path for Windows

CHANGELOG.md, Source/SourceKittenFramework/library_wrapper.swift
Currently, if Swift is installed in, say `/usr/lib/swift`, but `/usr/bin/swift`
has been symlinked to `/usr/lib/swift/bin/swift`, then SourceKitten will fail
to detect Swift's install directory. This PR fixes that, by reading symlinks
on the detected Swift executable.
=> fix(linux): detect swift symlinked to bin dir

Source/SourceKittenFramework/library_wrapper.swift
In this PR, it is invoked, like other commands, using `/usr/bin/env`.
=> fix(linux): do not assume the location of `which`

Source/SourceKittenFramework/SourceKitObject.swift, Source/SourceKittenFramework/UncheckedSendable.swift
Fixes #805
Introduce an [`UncheckedSendable`](https://github.com/pointfreeco/swift-concurrency-extras?tab=readme-ov-file#uncheckedsendable) type for wrapping non-sendable types in a `@Sendable` context. 
More context on why unsafe pointer types are no longer Sendable: https://forums.swift.org/t/unsafepointer-sendable-should-be-revoked/51926
The [change was merged](https://github.com/apple/swift/pull/39218) some time ago and only the warning is new in Xcode 15.3 betas so the behavior shouldn't be affected by this change.
`extension UnsafeMutablePointer: @unchecked Sendable {}` would've also silenced the warning but would go against the points made in the forums discussion. Keeping the `UncheckedSendable` wrapper forces to acknowledge the context and solution.
Open to try different …
=> Introduce `UncheckedSendable` type for wrapping non-sendable types

Package.resolved, Package.swift
This lower version number is preventing packages from using [SwiftLint](https://github.com/realm/SwiftLint) and the [Swift OpenAPI Generator](https://github.com/apple/swift-openapi-generator) in the same package.
=> Allow Swift Argument Parser versions from 1.2.1 to 2.0.0

.github/workflows/bazel.yml, MODULE.bazel, Source/BUILD
This does force users using this version of sourcekitten to also use rules_swift because of the `swift_c_module` removal.
Outstanding issues:
Requires the following:
- https://github.com/jpsim/Yams/pull/420
=> Adds support for rules_swift 2.x.

.github/workflows/jazzy.yml, Source/SourceKittenFramework/Clang+SourceKitten.swift
This otherwise causes a warning with a Swift 6 compiler (not necessarily the language mode).
=> Use @retroactive conformance

CHANGELOG.md, Source/SourceKittenFramework/JSONOutput.swift
We've never had straight arrays of strings before, this is new in Swift 6 (`"key.educational_note_paths"`):
```json
{
"\/Users\/johnf\/project\/JazzyEx\/JazzyEx\/JazzyEx.swift" : {
"key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
"key.diagnostics" : [
{
"key.column" : 12,
"key.description" : "extraneous whitespace between attribute name and '('; this is an error in the Swift 6 language mode",
"key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
"key.educational_note_paths" : [
"error-in-future-swift-version.md"
],
"key.id" : "error_in_future_swift_version",
"key.line" : 2,
"key.severity" : "source.diagnostic.severity.warning"
}
],
"key.length" : 43,
...
```
Attempt refactor to remove the assumption causing the force-unwrap fail.  New version runs the breaking …
=> Handle key.educational_note_paths in SourceKit output

CHANGELOG.md, Source/SourceKittenFramework/SourceKitObject.swift, Source/SourceKittenFramework/SwiftDocs.swift, Source/sourcekitten/main.swift
This allows compilation with the [static Linux SDK](https://www.swift.org/documentation/articles/static-linux-getting-started.html) in project consuming SourceKitten as a dependency.
=> Support Musl C standard library

CHANGELOG.md, Package.swift
When I tried to build my project using Xcode 16, I got an error:
```bash
error: 'sourcekitten': dependency 'Yams' in target 'SourceKittenFramework' requires explicit declaration; reference the package in the target dependency with '.product(name: "Yams", package: "yams")'
make: *** [build] Error 1
```
=> SPM: Explicit declarations for external dependencies

.bcr/presubmit.yml
These changes were also applied to the [previous successful Bazel release](https://github.com/bazelbuild/bazel-central-registry/pull/2504).
=> Simplify Bazel verification

MODULE.bazel
Update `max_compatibility_level` for rules_swift and update dependencies to do the same.
=> Support rules_swift 3.0
